export type AvemQuestion = {
  number: number;
  text: string;
};

export const AVEM_QUESTIONS: AvemQuestion[] = [
  { number: 1, text: 'Die Arbeit ist für mich der wichtigste Lebensinhalt.' },
  { number: 2, text: 'Ich möchte beruflich weiter kommen, als es die meisten meiner Bekannten geschafft haben.' },
  { number: 3, text: 'Wenn es sein muss, arbeite ich bis zur Erschöpfung.' },
  { number: 4, text: 'Meine Arbeit soll stets ohne Fehl und Tadel sein.' },
  { number: 5, text: 'Zum Feierabend ist die Arbeit für mich vergessen.' },
  { number: 6, text: 'Wenn ich keinen Erfolg habe, resigniere ich schnell.' },
  { number: 7, text: 'Für mich sind Schwierigkeiten dazu da, dass ich sie überwinde.' },
  { number: 8, text: 'Mich bringt so leicht nichts aus der Ruhe.' },
  { number: 9, text: 'Mein bisheriges Berufsleben war recht erfolgreich.' },
  { number: 10, text: 'Mit meinem bisherigen Leben kann ich zufrieden sein.' },
  { number: 11, text: 'Mein Partner/meine Partnerin zeigt Verständnis für meine Arbeit.' },
  { number: 12, text: 'Die Arbeit ist mein Ein und Alles.' },
  { number: 13, text: 'Berufliche Karriere bedeutet mir wenig.' },
  { number: 14, text: 'Bei der Arbeit kenne ich keine Schonung.' },
  { number: 15, text: 'Ich kontrolliere lieber noch dreimal nach, als dass ich fehlerhafte Arbeitsergebnisse abliefere.' },
  { number: 16, text: 'Auch in der Freizeit beschäftigen mich viele Arbeitsprobleme.' },
  { number: 17, text: 'Misserfolge kann ich nur schwer verkraften.' },
  { number: 18, text: 'Wenn mir etwas nicht gelingt, sage ich mir: „Jetzt erst recht!“' },
  { number: 19, text: 'Ich bin ein ruheloser Mensch.' },
  { number: 20, text: 'In meiner bisherigen Berufslaufbahn habe ich mehr Erfolge als Enttäuschungen erlebt.' },
  { number: 21, text: 'Im Großen und Ganzen bin ich glücklich und zufrieden.' },
  { number: 22, text: 'Meine Familie interessiert sich nur wenig für meine Arbeitsprobleme.' },
  { number: 23, text: 'Ich könnte auch ohne meine Arbeit ganz glücklich sein.' },
  { number: 24, text: 'Was meine berufliche Entwicklung angeht, so halte ich mich für ziemlich ehrgeizig.' },
  { number: 25, text: 'Ich arbeite wohl mehr, als ich sollte.' },
  { number: 26, text: 'Bei meiner Arbeit habe ich den Ehrgeiz, keinerlei Fehler zu machen.' },
  { number: 27, text: 'Nach der Arbeit kann ich ohne Probleme abschalten.' },
  { number: 28, text: 'Berufliche Fehlschläge können mich leicht entmutigen.' },
  { number: 29, text: 'Misserfolge werfen mich nicht um, sondern veranlassen mich zu noch stärkerer Anstrengung.' },
  { number: 30, text: 'Ich glaube, dass ich ziemlich hektisch bin.' },
  { number: 31, text: 'Wirkliche berufliche Erfolge sind mir bisher versagt geblieben.' },
  { number: 32, text: 'Ich habe allen Grund, meine Zukunft optimistisch zu sehen.' },
  { number: 33, text: 'Von meinem Partner/meiner Partnerin wünschte ich mir mehr Rücksichtnahme auf meine beruflichen Aufgaben und Probleme.' },
  { number: 34, text: 'Ich brauche die Arbeit wie die Luft zum Atmen.' },
  { number: 35, text: 'Ich strebe nach höheren beruflichen Zielen als die meisten anderen.' },
  { number: 36, text: 'Ich neige dazu, über meine Kräfte hinaus zu arbeiten.' },
  { number: 37, text: 'Was immer ich tue, es muss perfekt sein.' },
  { number: 38, text: 'Feierabend ist Feierabend, da verschwende ich keine Gedanken mehr an die Arbeit.' },
  { number: 39, text: 'Wenn ich in der Arbeit erfolglos bin, deprimiert mich das sehr.' },
  { number: 40, text: 'Ich bin mir sicher, dass ich auch die künftigen Anforderungen des Lebens gut bewältigen kann.' },
  { number: 41, text: 'Ich glaube, ich bin ein ruhender Pol in meinem Umfeld.' },
  { number: 42, text: 'In meiner beruflichen Entwicklung ist mir bisher fast alles gelungen.' },
  { number: 43, text: 'Ich kann mich über mein Leben in keiner Weise beklagen.' },
  { number: 44, text: 'Bei meiner Familie finde ich jede Unterstützung.' },
  { number: 45, text: 'Ich wüsste nicht, wie ich ohne Arbeit leben sollte.' },
  { number: 46, text: 'Für meine berufliche Zukunft habe ich mir viel vorgenommen.' },
  { number: 47, text: 'Mein Tagesablauf ist durch chronischen Zeitmangel bestimmt.' },
  { number: 48, text: 'Für mich ist die Arbeit erst dann getan, wenn ich rundum mit dem Ergebnis zufrieden bin.' },
  { number: 49, text: 'Arbeitsprobleme beschäftigen mich eigentlich den ganzen Tag.' },
  { number: 50, text: 'Ich verliere leicht den Mut, wenn ich trotz Anstrengung keinen Erfolg habe.' },
  { number: 51, text: 'Ein Misserfolg kann bei mir neue Kräfte wecken.' },
  { number: 52, text: 'Ich kann mich in fast allen Situationen ruhig und bedächtig verhalten.' },
  { number: 53, text: 'Mein bisheriges Leben ist durch beruflichen Erfolg gekennzeichnet.' },
  { number: 54, text: 'Von manchen Seiten des Lebens bin ich ziemlich enttäuscht.' },
  { number: 55, text: 'Manchmal wünschte ich mir mehr Unterstützung durch die Menschen meiner Umgebung.' },
  { number: 56, text: 'Es gibt Wichtigeres im Leben als die Arbeit.' },
  { number: 57, text: 'Beruflicher Erfolg ist für mich ein wichtiges Lebensziel.' },
  { number: 58, text: 'In der Arbeit verausgabe ich mich stark.' },
  { number: 59, text: 'Es widerstrebt mir, wenn ich eine Arbeit abschließen muss, obwohl sie noch verbessert werden könnte.' },
  { number: 60, text: 'Meine Gedanken kreisen fast nur um die Arbeit.' },
  { number: 61, text: 'Wenn ich irgendwo versagt habe, kann mich das ziemlich mutlos machen.' },
  { number: 62, text: 'Wenn mir etwas nicht gelingt, bleibe ich hartnäckig und strenge mich umso mehr an.' },
  { number: 63, text: 'Hektik und Aufregung um mich herum lassen mich kalt.' },
  { number: 64, text: 'Meine beruflichen Leistungen können sich sehen lassen.' },
  { number: 65, text: 'Es dürfte nur wenige glücklichere Menschen geben, als ich es bin.' },
  { number: 66, text: 'Wenn ich mal Rat und Hilfe brauche, ist immer jemand da.' },
];