export interface AVEMQuestion {
    number: number;
    text: string;
}

// TODO: Replace placeholder texts with actual AVEM questionnaire items
export const AVEM_QUESTIONS: AVEMQuestion[] = [
    { number: 1, text: 'Frage 1' },
    { number: 2, text: 'Frage 2' },
    { number: 3, text: 'Frage 3' },
    { number: 4, text: 'Frage 4' },
    { number: 5, text: 'Frage 5' },
    { number: 6, text: 'Frage 6' },
    { number: 7, text: 'Frage 7' },
    { number: 8, text: 'Frage 8' },
    { number: 9, text: 'Frage 9' },
    { number: 10, text: 'Frage 10' },
    { number: 11, text: 'Frage 11' },
    { number: 12, text: 'Frage 12' },
    { number: 13, text: 'Frage 13' },
    { number: 14, text: 'Frage 14' },
    { number: 15, text: 'Frage 15' },
    { number: 16, text: 'Frage 16' },
    { number: 17, text: 'Frage 17' },
    { number: 18, text: 'Frage 18' },
    { number: 19, text: 'Frage 19' },
    { number: 20, text: 'Frage 20' },
    { number: 21, text: 'Frage 21' },
    { number: 22, text: 'Frage 22' },
    { number: 23, text: 'Frage 23' },
    { number: 24, text: 'Frage 24' },
    { number: 25, text: 'Frage 25' },
    { number: 26, text: 'Frage 26' },
    { number: 27, text: 'Frage 27' },
    { number: 28, text: 'Frage 28' },
    { number: 29, text: 'Frage 29' },
    { number: 30, text: 'Frage 30' },
    { number: 31, text: 'Frage 31' },
    { number: 32, text: 'Frage 32' },
    { number: 33, text: 'Frage 33' },
    { number: 34, text: 'Frage 34' },
    { number: 35, text: 'Frage 35' },
    { number: 36, text: 'Frage 36' },
    { number: 37, text: 'Frage 37' },
    { number: 38, text: 'Frage 38' },
    { number: 39, text: 'Frage 39' },
    { number: 40, text: 'Frage 40' },
    { number: 41, text: 'Frage 41' },
    { number: 42, text: 'Frage 42' },
    { number: 43, text: 'Frage 43' },
    { number: 44, text: 'Frage 44' },
    { number: 45, text: 'Frage 45' },
    { number: 46, text: 'Frage 46' },
    { number: 47, text: 'Frage 47' },
    { number: 48, text: 'Frage 48' },
    { number: 49, text: 'Frage 49' },
    { number: 50, text: 'Frage 50' },
    { number: 51, text: 'Frage 51' },
    { number: 52, text: 'Frage 52' },
    { number: 53, text: 'Frage 53' },
    { number: 54, text: 'Frage 54' },
    { number: 55, text: 'Frage 55' },
    { number: 56, text: 'Frage 56' },
    { number: 57, text: 'Frage 57' },
    { number: 58, text: 'Frage 58' },
    { number: 59, text: 'Frage 59' },
    { number: 60, text: 'Frage 60' },
    { number: 61, text: 'Frage 61' },
    { number: 62, text: 'Frage 62' },
    { number: 63, text: 'Frage 63' },
    { number: 64, text: 'Frage 64' },
    { number: 65, text: 'Frage 65' },
    { number: 66, text: 'Frage 66' },
];
