import { Theater } from "lucide-vue-next";

export interface BIT2Question {
    number: number;
    text: string;
    group: string;
}

export const BIT2_QUESTIONS: BIT2Question[] = [
    { number: 1, text: 'Maschinen in neuen Fabriken montieren', group: 'TH' },
    { number: 2, text: 'Erfrischende Obstsalate aus Südfrüchten zubereiten', group: 'EH' },
    { number: 3, text: 'Formularwesen einer Verwaltung vereinfachen', group: 'VB' },
    { number: 4, text: 'Innenausstattung für ein neues Hotel aussuchen', group: 'GH' },
    { number: 5, text: 'Tannenwälder aufforsten', group: 'LF' },
    { number: 6, text: 'Im Fernsehen über neue Bücher berichten', group: 'LG' },
    { number: 7, text: 'Verwendbarkeit von Kunststoffen prüfen', group: 'TN' },
    { number: 8, text: 'Urlaubswünsche von Kunden für ein Reisebüro erheben', group: 'KB' },
    { number: 9, text: 'Selbstmordgefährdete beraten', group: 'SE' },
    { number: 10, text: 'Im Tagebau Braunkohle fördern', group: 'TH' },
    { number: 11, text: 'Sauberkeitsvorschriften im Lebensmittelgewerbe überwachen', group: 'EH' },
    { number: 12, text: 'Warenein- und Ausgänge einer Firma kontrollieren', group: 'VB' },
    { number: 13, text: 'Bühnenkulissen malen', group: 'GH' },
    { number: 14, text: 'Eine Bienenzucht anlegen', group: 'LF' },
    { number: 15, text: 'Artikel für Illustrierte schreiben', group: 'LG' },
    { number: 16, text: 'Kameras für plastisches Fernsehen entwickeln', group: 'TN' },
    { number: 17, text: 'Preisentwicklung der Konkurrenz für eine Firma beobachten', group: 'KB' },
    { number: 18, text: 'Kriminelle Jugendliche zum Guten führen', group: 'SE' },
    { number: 19, text: 'Kurbelwellen für Autos drehen', group: 'TH' },
    { number: 20, text: 'Geschmack verschiedener Teesorten vergleichen', group: 'EH' },
    { number: 21, text: 'Zulassungsanträge für Kraftfahrzeuge bearbeiten', group: 'VB' },
    { number: 22, text: 'Bauzeichnungen für Terrassenhäuser durchführen', group: 'GH' },
    { number: 23, text: 'Bauernhöfe auf Gewächshausanbau vorbereiten', group: 'LF' },
    { number: 24, text: 'Zeitkritische Theaterstücke schreiben', group: 'LG' },
    { number: 25, text: 'Energieausstrahlung neuer Sterne messen', group: 'TN' },
    { number: 26, text: 'Zeitungswerbung für Zahnpasta durchführen', group: 'KB' },
    { number: 27, text: 'Kinder mit Behinderung auf die Schule vorbereiten', group: 'SE' },
    { number: 28, text: 'Dieselmotoren reparieren', group: 'TH' },
    { number: 29, text: 'In Molkereien Bakterienfreiheit der Milch überwachen', group: 'EH' },
    { number: 30, text: 'In Warenlager Bestandslisten anfertigen', group: 'VB' },
    { number: 31, text: 'Tapetenmuster entwerfen', group: 'GH' },
    { number: 32, text: 'Tiere in einem Zoo pflegen', group: 'LF' },
    { number: 33, text: 'Geschichtsbuch über Raubritterzeit schreiben', group: 'LG' },
    { number: 34, text: 'In elektronischem Labor arbeiten', group: 'TN' },
    { number: 35, text: 'Für Ferienreisen nach Italien werben', group: 'KB' },
    { number: 36, text: 'Kinder berufstätiger Mütter beaufsichtigen', group: 'SE' },
    { number: 37, text: 'In Fahrradfabrik Rahmen schweißen', group: 'TH' },
    { number: 38, text: 'Sachgemäße Lagerung von Fleisch im Kühlhaus überwachen', group: 'EH' },
    { number: 39, text: 'Kundenkartei im Großhandel bearbeiten', group: 'VB' },
    { number: 40, text: 'Armbänder aus Gold schmieden', group: 'GH' },
    { number: 41, text: 'Brachliegendes Ackerland neu kultivieren', group: 'LF' },
    { number: 42, text: 'Politiker im Fernsehen interviewen', group: 'LG' },
    { number: 43, text: 'Elektrische Spannungen von Blitzen messen', group: 'TN' },
    { number: 44, text: 'Verkäufer zu gutem Kundendienst anleiten', group: 'KB' },
    { number: 45, text: 'Arbeitsplätze für Haftentlassene besorgen', group: 'SE' },
    { number: 46, text: 'Autoscheinwerfer einbauen', group: 'TH' },
    { number: 47, text: 'Neue Erfrischungsgetränke erfinden', group: 'EH' },
    { number: 48, text: 'In einem Finanzamt Steuereinnahmen berechnen', group: 'VB' },
    { number: 49, text: 'Modeschmuck emaillieren', group: 'GH' },
    { number: 50, text: 'Forellen fischen', group: 'LF' },
    { number: 51, text: 'Themen der Gegenwartsdichtung untersuchen', group: 'LG' },
    { number: 52, text: 'Neue Kunststoffe entwickeln', group: 'TN' },
    { number: 53, text: 'Für Kunden Kunstgegenstände günstig ersteigern', group: 'KB' },
    { number: 54, text: 'Erblindete Kraftfahrer neue Berufe lehren', group: 'SE' },
    { number: 55, text: 'Werkzeuge schmieden', group: 'TH' },
    { number: 56, text: 'Neue Rezepte für eine Pralinenherstellung probieren', group: 'EH' },
    { number: 57, text: 'Im Kaufhaus Kundenkonten abrechnen', group: 'VB' },
    { number: 58, text: 'Pläne für Sitzmöbel entwerfen', group: 'GH' },
    { number: 59, text: 'Tropische Pflanzen in Botanischen Gärten züchten', group: 'LF' },
    { number: 60, text: 'Zeitungsberichte über neue Filme verfassen', group: 'LG' },
    { number: 61, text: 'Flugbahn von Raketen vorausberechnen', group: 'TN' },
    { number: 62, text: 'Grundstücke für Eigenheiminteressenten aufkaufen', group: 'KB' },
    { number: 63, text: 'Erholungsaufenthalte für Kranke vermitteln', group: 'SE' },
    { number: 64, text: 'Ferngasleitungen legen', group: 'TH' },
    { number: 65, text: 'Speisepläne für Kantinen aufstellen', group: 'EH' },
    { number: 66, text: 'Gehalts- und Lohnabrechnungen durchführen', group: 'VB' },
    { number: 67, text: 'Glückwunschkarten zeichnen', group: 'GH' },
    { number: 68, text: 'Bäume zum Fällen aussuchen', group: 'LF' },
    { number: 69, text: 'Fremdsprachige Romane übersetzen', group: 'LG' },
    { number: 70, text: 'Tragfähigkeit von Eisenträgern berechnen', group: 'TN' },
    { number: 71, text: 'Kartenverkauf für Zirkus organisieren', group: 'KB' },
    { number: 72, text: 'Die Fähigkeiten geistig Behinderter herausfinden', group: 'SE' },
    { number: 73, text: 'In Schiffswerft Hochseeyachten zimmern', group: 'TH' },
    { number: 74, text: 'Eine Milchbar einrichten', group: 'EH' },
    { number: 75, text: 'Verwaltungsakten bearbeiten', group: 'VB' },
    { number: 76, text: 'Werbeplakate für ein Parfüm entwerfen', group: 'GH' },
    { number: 77, text: 'Wildbestand eines Forstes hegen', group: 'LF' },
    { number: 78, text: 'Volkshochschulkurse über Geschichte halten', group: 'LG' },
    { number: 79, text: 'In meteorologischem Institut arbeiten', group: 'TN' },
    { number: 80, text: 'Versteigerungen leiten', group: 'KB' },
    { number: 81, text: 'Schwererziehbare Kinder betreuen', group: 'SE' },
];